version: '3'
services: 
  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"    
  config:
    image: spring-starter-config
    ports:
      - "8091:8091"
    command: >
      bash -c "/usr/local/src/wait-for-it.sh --timeout=0 rabbit:5672 -- java -jar -Dspring.cloud.config.server.git.username=rodrigoruizbaca -Dspring.cloud.config.server.git.password=r0dr1g0rrbR005 -Dspring.profiles.active=docker Configuration-0.0.1-SNAPSHOT-spring-boot.jar"
  discovery:
    image: spring-starter-discovery
    ports:
      - "8092:8092"
    command: >
      bash -c "/usr/local/src/wait-for-it.sh --timeout=0 config:8091 -- java -jar -Dspring.profiles.active=docker Discovery-0.0.1-SNAPSHOT-spring-boot.jar"
  gateway:
    image: spring-starter-gateway
    ports:
      - "8094:8094"
    command: >
      bash -c "/usr/local/src/wait-for-it.sh --timeout=0 discovery:8092 -- java -jar -Dspring.profiles.active=docker Gateway-0.0.1-SNAPSHOT-spring-boot.jar"
  auth:
    image: spring-starter-auth
    ports:
      - "8090:8090"
    command: >
      bash -c "/usr/local/src/wait-for-it.sh --timeout=0 gateway:8094 -- java -jar -DisMaster=true -Dspring.profiles.active=docker AuthService-0.0.1-SNAPSHOT-spring-boot.jar"