server:
  port: 8081
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rodrigoruizbaca/spring-cloud-microservices-starter.git
          searchPaths: config-files
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest