server:
  port: 9090
spring:
  cloud:
    bus:
      enabled: true  
  data:
    mongo:
      uri: mongodb+srv://starter:starter@cluster0-lpgfm.mongodb.net/test?retryWrites=true  
      databaseName: auth
  application:
    name: auth
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false  
eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId:
        ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/    
services:
  auth:
    name: auth