server:
  port: 9090
spring:
  cloud:
    bus:
      enabled: true  
  data:
    mongo:
      uri: mongodb://localhost:27017
      databaseName: spring
  application:
    name: auth
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include:
          bus-refresh  
eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId:
        ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/    
services:
  auth:
    name: auth
