server:
  port: 8094
spring:
  cloud:
    bus:
      enabled: true
  application:
    name: gateway
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include:
          bus-refresh  
eureka:
  instance:
    hostname: gateway
    metadataMap:
      instanceId:
        ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://discovery:8092/eureka/ 
    region: defaukt
    registryFetchIntervalSeconds: 5   

zuul:
  routes:
    auth:
      path: /auth/**
      sensitive-headers: Cookie,Set-Cookie
